---
- name: Add in memory host
  hosts: localhost 
  tasks:
    - name: Add undercloud to in-memory inventory
      add_host:
         name="{{ host.name }}"
         hostname="{{ host.ip }}"
         groups="all,undercloud,tester,local"
         ansible_ssh_host="{{ host.ip }}"
         ansible_fqdn="{{ host.ip }}"
         ansible_ssh_user="{{ host.username }}"
         ansible_ssh_private_key_file="{{ host.key_file }}"

- name: Patch and repackage components RPM
  hosts: undercloud 
  roles:
    - { role: setup_repos }
    - { role: setup_environment}
    - { role: setup_IT_certificates, become: yes }
    - { role: patch_rpm }

