---
- name: Patch and repackage components RPM
  hosts: [undercloud, tester, local]
  roles:
    - { role: patch }
    - { role: setup_repos }
    - { role: setup_environment }
    - { role: patch_rpm }

