---

- name: Red Hat IT Root CA certificate 
  become: yes
  get_url:
    url: "{{ item }}"
    dest: /etc/pki/ca-trust/source/anchors
  with_items:
      - 'https://password.corp.redhat.com/legacy.crt'
      - 'https://password.corp.redhat.com/RH-IT-Root-CA.crt'

- file:
    path: /etc/openldap/cacerts
    state: directory
    mode: 0755

- name: Red Hat IT Root CA certificate 
  become: yes
  get_url:
    url: "{{ item }}"
    dest: /etc/openldap/cacerts
  with_items:
      - 'https://password.corp.redhat.com/legacy.crt'
      - 'https://password.corp.redhat.com/RH-IT-Root-CA.crt'


- name: Update certificates
  become: yes
  shell: >
    {{ item }}
  with_items:
    - 'cacertdir_rehash /etc/openldap/cacerts'
    - 'update-ca-trust'
